-- user
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
	id bigint generated by default as identity,
	username varchar(40) not null unique,
	password varchar(40) not null,
	create_time datetime,
	update_time datetime,
	primary key (id)
);

-- role
DROP TABLE IF EXISTS `role`;
CREATE TABLE `role` (
	id bigint generated by default as identity,
	name varchar(20) not null,
	comment varchar(40),
	primary key (id)
);

-- user_rel_role
DROP TABLE IF EXISTS `user_rel_role`;
CREATE TABLE `user_rel_role` (
	id bigint generated by default as identity,
	user_id integer not null,
	role_id integer not null,
	primary key (id)
);

-- project
DROP TABLE IF EXISTS `project`;
CREATE TABLE `project` (
    id bigint generated by default as identity,
    name varchar(30) not null,
    war_name varchar(30) not null,
    deploy_script_type int default 1,
    primary key (id)
);

-- patch_file
DROP TABLE IF EXISTS `patch_file`;
CREATE TABLE `patch_file` (
    id bigint generated by default as identity,
    `project_id` bigint not null,
    `file_path` varchar(196) not null unique,
    primary key (id)
);

